WebChat/Models/ErrorViewModel.cs
namespace WebChat.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebChat/Controllers/ChatController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebChat.ChatEntities;
using WebChat.DB_Context;

namespace WebChat.Controllers
{
    public class ChatController : Controller
    {
        private readonly ChatRepository chatRepository;
        //храним дату и время
        public DateTime startDateTime;
        public ChatController(ChatRepository chatRepository)
        {
            startDateTime = DateTime.Now;
            this.chatRepository = chatRepository;
            
        }

        // GET: DialogController
        public ActionResult Dialog()
        {
            ViewBag.Messages = new List<string>();
            var messages = chatRepository.GetMessages();
            foreach (var message in messages)
            {
                ViewBag.Messages.Add(message.Value);
            }
            //var timer = new Timer(UpdateView, null, 0, 2000);
            return View();
        }
        public void UpdateView(string message)
        {
            ViewBag.Messages = new List<string>();
            //var messages = chatRepository.GetMessages();
            //foreach (var message in messages)
            //{
            //    ViewBag.Messages.Add(message.Value);
            //}
        }

    }
}

WebChat/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebChat.Models;

namespace WebChat.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebChat/Views/Chat/Dialog.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Dialog</title>
	<link rel="stylesheet" type="text/css" href="~/css/dialog.css">
</head>
<body>
	<div class='chat'>
		<div class='chat-messages'>
			<div class='chat-messages__content' id='messages'>
				@foreach (string message in ViewBag.Messages)
				{
					<p>@message</p>
				}
			</div>
		</div>
		<div class='chat-input'>
			<form method='post' id='chat-form'>
				<input type='text' id="message-text" class='chat-form__input' placeholder='Введите сообщение'> <input type='submit' class='chat-form__submit' value='=>'>
			</form>
		</div>
	</div>
	<script>
		var messages__container = document.getElementById('messages');
		//Контейнер сообщений — скрипт будет добавлять в него сообщения

		var interval = null; //Переменная с интервалом подгрузки сообщений

		var sendForm = document.getElementById('chat-form'); //Форма отправки
		var messageInput = document.getElementById('message-text');//Инпут для текста сообщения

		async function send( message, dialogId) {
			const response = await fetch("api/send_mes", {
				method: "POST",
				headers: { "Accept": "application/json", "Content-Type": "application/json" },
				body: JSON.stringify({
					value: message.value,
					isDeleted: false,
					senderId: 1,
					receiverId: 2
				})
			});
			if (response.ok === true) {
				const mess = await response.json();
				$.ajax({
					url: "@Url.Action( "Dialog", "Chat" )",
					//data: { message: $("#message-text").val() },
					type: 'POST',
					cache: false
            });
				//document.querySelector("tbody").append(row(user));
			}
			else {
				const error = await response.json();
				console.log(error.message);
			}
		}
		function update() {
			//const response = await fetch("Chat/Update",{});
		}
		interval = setInterval(update, 500);
		
		sendForm.onsubmit = function () {
			send( messageInput, 1);
			//$.ajax({
			//	url: 'Chat/Update'
			//}).done(function () {
			//	alert('Added');
			//});
			//const response = await fetch("Chat/Update", {});
			return false; //Возвращаем ложь, чтобы остановить классическую отправку формы
		};
		//function row(user) {

		//	const tr = document.createElement("tr");
		//	tr.setAttribute("data-rowid", user.id);

		//	const nameTd = document.createElement("td");
		//	nameTd.append(user.name);
		//	tr.append(nameTd);

		//	const emailTd = document.createElement("td");
		//	emailTd.append(user.email);
		//	tr.append(emailTd);

		//	const passTd = document.createElement("td");
		//	passTd.append(user.password);
		//	tr.append(passTd);

		//	const linksTd = document.createElement("td");

		//	const editLink = document.createElement("button");
		//	editLink.append("Изменить");
		//	editLink.addEventListener("click", async () => await getUser(user.id));
		//	linksTd.append(editLink);

		//	const removeLink = document.createElement("button");
		//	removeLink.append("Удалить");
		//	removeLink.addEventListener("click", async () => await deleteUser(user.id));

		//	linksTd.append(removeLink);
		//	tr.appendChild(linksTd);

		//	return tr;
		//}

	</script>
</body>
</html>

WebChat/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>UsersInfo</title>
    <style>
        td {
            padding: 5px;
        }

        button {
            margin: 5px;
        }
    </style>
</head>
<body>
    <h2>Список пользователей</h2>
    <div>
        <input type="hidden" id="userId" />
        <p>
            Имя:<br />
            <input id="userName" />
        </p>
        <p>
            Почта:<br />
            <input id="userEmail" />
        </p>
        <p>
            Пароль:<br />
            <input id="userPassword" />
        </p>
        <p>
            <button id="saveBtn">Сохранить</button>
            <button id="resetBtn">Сбросить</button>
        </p>
    </div>
    <table>
        <thead><tr><th>Имя</th><th>Email</th><th>Password</th><th></th></tr></thead>
        <tbody>
        </tbody>
    </table>

    <script>
        // Получение всех пользователей
        async function getUsers() {
            // отправляет запрос и получаем ответ
            const response = await fetch("/api/users", {
                method: "GET",
                headers: { "Accept": "application/json" }
            });
            // если запрос прошел нормально
            if (response.ok === true) {
                // получаем данные
                const users = await response.json();
                const rows = document.querySelector("tbody");
                // добавляем полученные элементы в таблицу
                users.forEach(user => rows.append(row(user)));
            }
        }
        // Получение одного пользователя
        async function getUser(id) {
            const response = await fetch(`/api/users/${id}`, {
                method: "GET",
                headers: { "Accept": "application/json" }
            });
            if (response.ok === true) {
                const user = await response.json();
                document.getElementById("userId").value = user.id;
                document.getElementById("userName").value = user.name;
                document.getElementById("userEmail").value = user.email;
                document.getElementById("userPassword").value = user.password;
            }
            else {
                // если произошла ошибка, получаем сообщение об ошибке
                const error = await response.json();
                console.log(error.message); // и выводим его на консоль
            }
        }
        // Добавление пользователя
        async function createUser(userName, userEmail, userPassword) {

            const response = await fetch("api/users", {
                method: "POST",
                headers: { "Accept": "application/json", "Content-Type": "application/json" },
                body: JSON.stringify({
                    name: userName,
                    email: userEmail,
                    password: userPassword
                })
            });
            if (response.ok === true) {
                const user = await response.json();
                document.querySelector("tbody").append(row(user));
            }
            else {
                const error = await response.json();
                console.log(error.message);
            }
        }
        // Изменение пользователя
        async function editUser(userId, userName, userEmail, userPassword) {
            const response = await fetch("api/users", {
                method: "PUT",
                headers: { "Accept": "application/json", "Content-Type": "application/json" },
                body: JSON.stringify({
                    id: userId,
                    name: userName,
                    email: userEmail,
                    password: userPassword
                })
            });
            if (response.ok === true) {
                const user = await response.json();
                document.querySelector(`tr[data-rowid='${user.id}']`).replaceWith(row(user));
            }
            else {
                const error = await response.json();
                console.log(error.message);
            }
        }
        // Удаление пользователя
        async function deleteUser(id) {
            const response = await fetch(`/api/users/${id}`, {
                method: "DELETE",
                headers: { "Accept": "application/json" }
            });
            if (response.ok === true) {
                const user = await response.json();
                document.querySelector(`tr[data-rowid='${user.id}']`).remove();
            }
            else {
                const error = await response.json();
                console.log(error.message);
            }
        }

        // сброс данных формы после отправки
        function reset() {
            document.getElementById("userId").value =
                document.getElementById("userName").value =
                document.getElementById("userEmail").value =
                document.getElementById("userPassword").value = "";
        }
        // создание строки для таблицы
        function row(user) {

            const tr = document.createElement("tr");
            tr.setAttribute("data-rowid", user.id);

            const nameTd = document.createElement("td");
            nameTd.append(user.name);
            tr.append(nameTd);

            const emailTd = document.createElement("td");
            emailTd.append(user.email);
            tr.append(emailTd);

            const passTd = document.createElement("td");
            passTd.append(user.password);
            tr.append(passTd);

            const linksTd = document.createElement("td");

            const editLink = document.createElement("button");
            editLink.append("Изменить");
            editLink.addEventListener("click", async () => await getUser(user.id));
            linksTd.append(editLink);

            const removeLink = document.createElement("button");
            removeLink.append("Удалить");
            removeLink.addEventListener("click", async () => await deleteUser(user.id));

            linksTd.append(removeLink);
            tr.appendChild(linksTd);

            return tr;
        }
        // сброс значений формы
        document.getElementById("resetBtn").addEventListener("click", () => reset());

        // отправка формы
        document.getElementById("saveBtn").addEventListener("click", async () => {

            const id = document.getElementById("userId").value;
            const name = document.getElementById("userName").value;
            const email = document.getElementById("userEmail").value;
            const password = document.getElementById("userPassword").value;
            if (id === "")
                await createUser(name, email, password);
            else
                await editUser(id, name, email, password);
            reset();
        });

        // загрузка пользователей
        getUsers();
    </script>
</body>
</html>

WebChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebChat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebChat.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebChat</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebChat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>